channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - psycopg2

  # dev dependencies
  - ruff
  - mypy
  - pytest
  - black
  - isort
  - yamllint
  
  # pip itself
  - pip
  - pip:
      - dagster==1.4.5
      - dagster-dbt==0.20.5
      - dagster-webserver==1.4.5
      - dbt-postgres==1.6.0
      - dbt-duckdb==1.6.0
      - sqlfluff==2.3.0
      - sqlfluff-templater-dbt==2.3.0
